export const countryCodes = [
  { code: '+1', country: 'United States/Canada', iso: 'US', pattern: /^\d{10}$/ },
  { code: '+44', country: 'United Kingdom', iso: 'GB', pattern: /^\d{10,11}$/ },
  { code: '+61', country: 'Australia', iso: 'AU', pattern: /^\d{9}$/ },
  { code: '+49', country: 'Germany', iso: 'DE', pattern: /^\d{10,11}$/ },
  { code: '+33', country: 'France', iso: 'FR', pattern: /^\d{9}$/ },
  { code: '+91', country: 'India', iso: 'IN', pattern: /^\d{10}$/ },
  { code: '+81', country: 'Japan', iso: 'JP', pattern: /^\d{10}$/ },
  { code: '+86', country: 'China', iso: 'CN', pattern: /^\d{11}$/ },
  { code: '+55', country: 'Brazil', iso: 'BR', pattern: /^\d{10,11}$/ },
  { code: '+52', country: 'Mexico', iso: 'MX', pattern: /^\d{10}$/ },
  { code: '+39', country: 'Italy', iso: 'IT', pattern: /^\d{10}$/ },
  { code: '+34', country: 'Spain', iso: 'ES', pattern: /^\d{9}$/ },
  { code: '+7', country: 'Russia', iso: 'RU', pattern: /^\d{10}$/ },
  { code: '+82', country: 'South Korea', iso: 'KR', pattern: /^\d{9,11}$/ },
  { code: '+31', country: 'Netherlands', iso: 'NL', pattern: /^\d{9}$/ },
  { code: '+46', country: 'Sweden', iso: 'SE', pattern: /^\d{7,13}$/ },
  { code: '+41', country: 'Switzerland', iso: 'CH', pattern: /^\d{9}$/ },
  { code: '+32', country: 'Belgium', iso: 'BE', pattern: /^\d{9}$/ },
  { code: '+43', country: 'Austria', iso: 'AT', pattern: /^\d{4,13}$/ },
  { code: '+47', country: 'Norway', iso: 'NO', pattern: /^\d{8}$/ },
  { code: '+45', country: 'Denmark', iso: 'DK', pattern: /^\d{8}$/ },
  { code: '+353', country: 'Ireland', iso: 'IE', pattern: /^\d{9}$/ },
  { code: '+64', country: 'New Zealand', iso: 'NZ', pattern: /^\d{8,10}$/ },
  { code: '+65', country: 'Singapore', iso: 'SG', pattern: /^\d{8}$/ },
  { code: '+971', country: 'UAE', iso: 'AE', pattern: /^\d{9}$/ },
  { code: '+966', country: 'Saudi Arabia', iso: 'SA', pattern: /^\d{9}$/ },
  { code: '+20', country: 'Egypt', iso: 'EG', pattern: /^\d{10}$/ },
  { code: '+27', country: 'South Africa', iso: 'ZA', pattern: /^\d{9}$/ },
  { code: '+234', country: 'Nigeria', iso: 'NG', pattern: /^\d{10}$/ },
  { code: '+254', country: 'Kenya', iso: 'KE', pattern: /^\d{9}$/ },
  { code: '+90', country: 'Turkey', iso: 'TR', pattern: /^\d{10}$/ },
  { code: '+92', country: 'Pakistan', iso: 'PK', pattern: /^\d{10}$/ },
  { code: '+62', country: 'Indonesia', iso: 'ID', pattern: /^\d{10,12}$/ },
  { code: '+60', country: 'Malaysia', iso: 'MY', pattern: /^\d{9,10}$/ },
  { code: '+63', country: 'Philippines', iso: 'PH', pattern: /^\d{10}$/ },
  { code: '+84', country: 'Vietnam', iso: 'VN', pattern: /^\d{9,10}$/ },
  { code: '+66', country: 'Thailand', iso: 'TH', pattern: /^\d{9}$/ },
];
